#!/bin/bash
set -e
set -o pipefail

# add group
if ! getent group | grep -q "^orecore:" ; then
    echo "Creating system group: orecore"
    groupadd --system orecore
fi

# add user
if ! getent passwd | grep -q "^orecore:"; then
    echo "Creating orecore system user"
    useradd --gid "orecore" --system -m orecore
fi

# build nodejs addons
cd "/usr/opt/orecore"
SKIP_BITCOIN_DOWNLOAD=1 npm rebuild

# setup data directory
mkdir -p "/home/orecore/.orecore/data"
chown -R orecore:orecore "/home/orecore/.orecore"

# start orecore
if hash service 2> /dev/null; then
    service orecore start || echo "orecore could not be registered or started"
elif hash start 2> /dev/null; then
    start orecore || echo "orecore could not be registered or started"
elif hash systemctl 2> /dev/null; then
    {
        systemctl enable "orecore.service" && \
            systemctl start "orecore.service"
    } || echo "orecore could not be registered or started"
else
    echo 'Your system does not appear to use upstart or systemd, so orecore could not be started'
fi
