#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service orecore stop || echo "orecore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "orecore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "orecore.service" || echo "orecore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so orecore could not be stopped"
fi
